name: BetterRewards
main: fernanACM\BetterRewards\Loader
version: 1.0.0
api: 4.0.0
author: fernanACM
description: "Daily and monthly rewards, depending on the day of the week. Available for PocketMine-MP 4.0 servers"
website: https://github.com/fernanACM

permissions:
  betterrewards.cmd.acm:
    default: true
  betterrewards.edit.acm:
    default: op